# Generated by Django 5.2.8 on 2025-11-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='confirmada', help_text='Estado actual de la reserva', max_length=20)),
                ('fecha', models.DateField(help_text='Fecha de la reserva')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la reserva')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la reserva')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio total de la reserva (calculado automáticamente)', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del deportista', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(help_text='Cancha reservada', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='canchas.cancha')),
                ('deportista', models.ForeignKey(help_text='Deportista que realiza la reserva', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='accounts.deportista')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='hora_fin_mayor_que_hora_inicio_reserva'), models.UniqueConstraint(fields=('cancha', 'fecha', 'hora_inicio'), name='unique_reserva_cancha_fecha_hora')],
            },
        ),
    ]
