# Generated by Django 5.2.8 on 2025-11-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_cancha_fecha_hora',
        ),
    ]
