# Generated by Django 5.2.8 on 2025-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_unique_reserva_cancha_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente')], default='confirmada', help_text='Estado actual de la reserva', max_length=20),
        ),
    ]
