# Generated by Django 5.2.8 on 2025-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada')], default='confirmada', help_text='Estado actual de la reserva', max_length=20),
        ),
    ]
