# Generated by Django 5.2.8 on 2025-11-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo de la cancha', max_length=100)),
                ('capacidad_jugadores', models.PositiveIntegerField(blank=True, help_text='Número máximo de jugadores', null=True)),
                ('superficie', models.CharField(blank=True, help_text='Tipo de superficie (ej: césped sintético, cemento)', max_length=50, null=True)),
                ('is_techada', models.BooleanField(default=False, help_text='Indica si la cancha está techada/cubierta')),
                ('is_activa', models.BooleanField(default=True, help_text='Indica si la cancha está activa para reservas')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la cancha', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(help_text='Club al que pertenece la cancha', on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='accounts.club')),
                ('deporte', models.ForeignKey(help_text='Deporte que se practica en esta cancha', on_delete=django.db.models.deletion.RESTRICT, related_name='canchas', to='core.deporte')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['club', 'nombre'],
                'unique_together': {('club', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TarifaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], help_text='Día de la semana (0=Domingo, 6=Sábado)')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de esta tarifa')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de esta tarifa')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por hora en esta franja', max_digits=10)),
                ('titulo', models.CharField(blank=True, help_text='Nombre descriptivo de la tarifa (ej: Tarifa Nocturna)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(help_text='Cancha a la que aplica esta tarifa', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='canchas.cancha')),
            ],
            options={
                'verbose_name': 'Tarifa de Cancha',
                'verbose_name_plural': 'Tarifas de Canchas',
                'ordering': ['cancha', 'dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='hora_fin_mayor_que_hora_inicio')],
            },
        ),
    ]
